server:
  port: 8080

#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      routes:
#        - id: users
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/api/users/**
#
#        - id: posts
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/api/posts/**
